# Generated by Django 4.2 on 2023-08-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosterApp', '0002_alter_sponsor_sponsorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='fullName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
