# Generated by Django 4.2 on 2023-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosterApp', '0003_alter_sponsor_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='address',
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardianId',
            field=models.CharField(max_length=10),
        ),
    ]
