# Generated by Django 4.2 on 2023-08-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosterApp', '0004_remove_child_guardian_remove_guardian_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='guardianId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rey', to='fosterApp.guardian'),
            preserve_default=False,
        ),
    ]
